export const locations = [
    {
        name: "Burger King's Parking",
        description: null,
        lat: 34.682333,
        lng: 33.0097412,
        price_per_hour: null,
        tariff: null,
    },
    {
        name: "Public Parking Entrance",
        description: null,
        lat: 34.6823325,
        lng: 33.0097412,
        price_per_hour: null,
        tariff: null,
    },
    {
        name: "Parking Lot",
        description: null,
        lat: 34.682332,
        lng: 33.0097412,
        price_per_hour: null,
        tariff: null,
    },
    {
        name: "Parking",
        description: null,
        lat: 34.6776395,
        lng: 32.9679219,
        price_per_hour: null,
        tariff: null,
    },
    {
        name: "Peratikos Private Parking",
        description: null,
        lat: 34.6776375,
        lng: 32.9679219,
        price_per_hour: null,
        tariff: null,
    },
    {
        name: "Molos Parking",
        description: null,
        lat: 34.6738892,
        lng: 33.0368372,
        price_per_hour: null,
        tariff: null,
    },
    {
        name: "Savvas Car Parking LTD",
        description: null,
        lat: 34.6823341,
        lng: 33.0097412,
        price_per_hour: null,
        tariff: null,
    },
    {
        name: "Parking area Spyru Arauzu - Old Port",
        description: null,
        lat: 34.6823314,
        lng: 33.0097412,
        price_per_hour: null,
        tariff: null,
    },
    {
        name: "Archiepiskopou Kyprianou 31 Parking",
        description: null,
        lat: 34.6823354,
        lng: 33.0097412,
        price_per_hour: null,
        tariff: null,
    },
    {
        name: "Public Parking",
        description: null,
        lat: 34.6823334,
        lng: 33.0097412,
        price_per_hour: null,
        tariff: null,
    },
    {
        name: "Salaminos Car Park - Daily, Monthly & Annual Tickets Available",
        description: null,
        lat: 34.6823334,
        lng: 33.0097412,
        price_per_hour: null,
        tariff: null,
    },
    {
        name: "Pefkos City Hotel Parking",
        description: null,
        lat: 34.6745483,
        lng: 32.9491148,
        price_per_hour: null,
        tariff: null,
    },
    {
        name: "Χώρος Στάθμευσης",
        description: null,
        lat: 34.6745483,
        lng: 32.9491148,
        price_per_hour: null,
        tariff: null,
    },
    {
        name: "Parking Lot",
        description: null,
        lat: 34.6745483,
        lng: 32.9491148,
        price_per_hour: null,
        tariff: null,
    },
    {
        name: "Parking space",
        description: null,
        lat: 34.6745483,
        lng: 32.9491148,
        price_per_hour: null,
        tariff: null,
    },
    // {
    //     name: "Public Parking space",
    //     description: null,
    //     lat: null,
    //     lng: null,
    //     price_per_hour: null,
    //     tariff: null,
    // },
];
